name: '2. Build Fedora for Nabu'

on:
  workflow_dispatch: # 允许手动触发

permissions:
  contents: write # 为了创建 Release

env:
  CONTAINER_IMAGE: ghcr.io/${{ github.repository_owner }}/fedora-nabu-builder:42
  ROOTFS_NAME: fedora-42-nabu-rootfs.img
  BUILD_VERSION: "42.2"

jobs:
  build_rootfs:
    runs-on: ubuntu-24.04-arm
    container:
      image: ghcr.io/${{ github.repository_owner }}/fedora-nabu-builder:42
      options: --privileged
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create aarch64 rootfs
        run: |
          cp ./scripts/2_create_rootfs.sh ./2_create_rootfs.sh
          chmod +x 2_create_rootfs.sh
          ./2_create_rootfs.sh

      - name: Upload rootfs artifact
        uses: actions/upload-artifact@v4
        with:
          name: rootfs-artifact
          path: ./${{ env.ROOTFS_NAME }}

  create_release:
    runs-on: ubuntu-24.04-arm
    needs: build_rootfs
    container:
      image: ghcr.io/${{ github.repository_owner }}/fedora-nabu-builder:42
      options: --privileged
    permissions:
      contents: write
    env:
      ROOTFS_NAME: fedora-42-nabu-rootfs.img
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      # 步骤 1: 先检出仓库，获取发布脚本
      - name: Checkout repository
        uses: actions/checkout@v4

      # 步骤 2: 再下载工件，它们会被放入已检出的工作目录中
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      # 步骤 3: 运行发布脚本，此时脚本和工件都已就绪
      # The script now handles the git 'dubious ownership' issue internally.
      - name: Create Release and Upload Assets
        run: |
          cp ./scripts/4_create_release.sh ./4_create_release.sh
          chmod +x 4_create_release.sh
          ./4_create_release.sh
